server:
  port: 8081

rego:
  client:
    address:
      url: http://address-service:8085/api/v1/addresses

spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal
