server:
  port: 8085

spring:
  application:
    name: address-service
  datasource:
    url: jdbc:postgresql://localhost:5432/addressdb
    username: address
    password: address
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: false
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info

# perfil para docker (sobrep√µe o datasource e host)
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/addressdb
    username: address
    password: address
